spring.application.name=QuizeApp


spring.datasource.url=jdbc:mysql://localhost:3306/quize_db
spring.datasource.username=root
spring.datasource.password=Om@021102
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
 

